import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('h1')).toContainText('A studying tool that\'s actually free');
  await expect(page.getByRole('banner')).toContainText('Sign in');
  await page.getByRole('link', { name: 'Get Started' }).click();
  await expect(page.locator('#account-div')).toContainText('Sign Up');
  await expect(page.locator('#account-div')).toContainText('Continue without an account');
  await expect(page.locator('#account-div')).toContainText('Already have an account? Sign in');
  await expect(page.getByRole('banner')).toContainText('Sign in');
  await page.getByRole('banner').getByRole('link', { name: 'Sign in' }).click();
  await expect(page.locator('#account-div')).toContainText('Sign In');
  await expect(page.locator('#account-div')).toContainText('Continue without an account');
  await expect(page.locator('#account-div')).toContainText('Sign up to create an account');
  await expect(page.getByRole('banner')).toContainText('Sign up');
  await page.locator('#account-div').getByRole('link', { name: 'Sign up' }).click();
  await expect(page.locator('#account-div')).toContainText('Sign Up');
  await page.getByRole('button', { name: 'Continue without an account' }).click();
  await expect(page.locator('#dashboard-noaccount-alert')).toContainText('You\'re not signed in, so your sets will be saved locally (on your device)');
  await expect(page.getByRole('main')).toContainText('Select "New Studyset" to enter or import terms');
  await page.getByRole('button', { name: 'New Studyset' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('New Studyset 1');
  await page.getByRole('textbox', { name: 'Term' }).click();
  await page.getByRole('textbox', { name: 'Term' }).fill('Term 1');
  await page.getByRole('textbox', { name: 'Definition' }).click();
  await page.getByRole('textbox', { name: 'Definition' }).fill('Def 1');
  await page.getByRole('button', { name: 'Add term' }).click();
  await page.getByRole('textbox', { name: 'Term' }).nth(1).fill('Term 2');
  await page.getByRole('textbox', { name: 'Definition' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Definition' }).nth(1).fill('Def 2');
  await page.getByRole('button', { name: 'Create' }).click();
  await expect(page.locator('#title-and-menu-outer-div')).toContainText('New Studyset 1');
  await expect(page.locator('#title-and-menu-outer-div')).toContainText('Local Studyset');
  await expect(page.locator('#edit-menu')).toContainText('Edit');
  await expect(page.locator('#flashcard-front')).toContainText('Term 1');
  await page.locator('#flashcard-front').click();
  await expect(page.locator('#flashcard-back')).toContainText('Def 1');
  await expect(page.locator('#flashcards-count')).toContainText('1/2');
  await expect(page.getByRole('rowgroup')).toContainText('Term 1');
  await expect(page.getByRole('rowgroup')).toContainText('Def 1');
  await expect(page.getByRole('rowgroup')).toContainText('Term 2');
  await expect(page.getByRole('rowgroup')).toContainText('Def 2');
  await page.getByRole('button', { name: 'Flip' }).click();
  await page.getByRole('button', { name: 'Next Card' }).click();
  await expect(page.locator('#flashcard-front')).toContainText('Term 2');
  await page.locator('#flashcard-front').click();
  await expect(page.locator('#flashcard-back')).toContainText('Def 2');
  await expect(page.getByRole('banner')).toContainText('Sign in');
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page.locator('#dashboard-noaccount-alert')).toContainText('You\'re not signed in, so your sets will be saved locally (on your device)');
  await expect(page.getByRole('main')).toContainText('New Studyset 1 2 Terms');
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('link', { name: 'Account' }).click();
  await expect(page.locator('#account-not-signedin-div')).toContainText('You\'re not signed in. Do you want to sign in or create an account?');
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('link', { name: 'New Studyset 1 2 Terms' }).click();
  await page.getByRole('button', { name: 'More Options Dropdown' }).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await expect(page.getByRole('main')).toContainText('Are you sure you want to delete this studyset?');
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page.getByRole('main')).toContainText('New Studyset 1 2 Terms');
  await page.getByRole('link', { name: 'New Studyset 1 2 Terms' }).click();
  await page.getByRole('button', { name: 'More Options Dropdown' }).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Delete' }).nth(1).click();
  await expect(page.getByRole('main')).toContainText('Select "New Studyset" to enter or import terms');
});
