import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.getByRole('link', { name: 'Get Started' }).click();
  await page.getByRole('button', { name: 'Continue without an account' }).click();
  await page.getByRole('button', { name: 'New Studyset' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('New Local Studyset');
  await page.getByRole('textbox', { name: 'Term' }).click();
  await page.getByRole('textbox', { name: 'Term' }).fill('Term 1');
  await page.getByRole('textbox', { name: 'Definition' }).click();
  await page.getByRole('textbox', { name: 'Definition' }).fill('Def 1');
  await page.getByRole('button', { name: 'Add term' }).click();
  await page.getByRole('textbox', { name: 'Term' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Term' }).nth(1).fill('Term 2');
  await page.getByRole('textbox', { name: 'Definition' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Definition' }).nth(1).fill('Def 2');
  await page.getByRole('button', { name: 'Create' }).click();
  await expect(page.locator('#title-and-menu-outer-div')).toContainText('New Local Studyset');
  await expect(page.locator('#title-and-menu-outer-div')).toContainText('Local Studyset');
  await expect(page.locator('#flashcard-front')).toContainText('Term 1');
  await page.locator('#flashcard-front').click();
  await expect(page.locator('#flashcard-back')).toContainText('Def 1');
  await page.getByRole('button', { name: 'Next Card' }).click();
  await expect(page.locator('#flashcard-back')).toContainText('Def 2');
  await page.locator('#flashcard-back').click();
  await expect(page.locator('#flashcard-front')).toContainText('Term 2');
  await expect(page.getByRole('rowgroup')).toContainText('Term 1');
  await expect(page.getByRole('rowgroup')).toContainText('Def 1');
  await expect(page.getByRole('rowgroup')).toContainText('Term 2');
  await expect(page.getByRole('rowgroup')).toContainText('Def 2');
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowDown');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Title' }).fill('Renamed Local Studyset');
  await page.getByRole('button', { name: 'Actions dropdown menu' }).first().click();
  await page.getByRole('button', { name: 'Move down' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.locator('#title-and-menu-outer-div')).toContainText('Renamed Local Studyset');
  await expect(page.locator('#flashcard-front')).toContainText('Term 2');
  await page.locator('#flashcard-front').click();
  await expect(page.locator('#flashcard-back')).toContainText('Def 2');
  await expect(page.locator('#title-and-menu-outer-div')).toContainText('Local Studyset');
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Title' }).fill('');
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.locator('#title-and-menu-outer-div')).toContainText('Untitled Studyset');
  await expect(page.locator('#title-and-menu-outer-div')).toContainText('Local Studyset');
  await page.getByRole('button', { name: 'More Options Dropdown' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page.getByRole('link', { name: 'Untitled Studyset 2 Terms' })).toBeVisible();
  await page.getByRole('link', { name: 'Untitled Studyset 2 Terms' }).click();
  await expect(page.locator('#title-and-menu-outer-div')).toContainText('Untitled Studyset');
  await expect(page.locator('#flashcard-front')).toContainText('Term 2');
  await page.locator('#flashcard-front').click();
  await expect(page.locator('#flashcard-back')).toContainText('Def 2');
  await page.getByRole('button', { name: 'More Options Dropdown' }).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Delete' }).nth(1).click();
});