version: "3"
services:
  postgres:
    image: docker.io/library/postgres:17.4-bookworm
    secrets:
      - quizfreely_postgres_admin_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/quizfreely_postgres_admin_password
  quizfreely_api:
    image: codeberg.org/quizfreely/quizfreely-api:0.31.0
    ports:
      - "8008:8008"
    links:
      - postgres
    secrets:
      - quizfreely_postgres_password
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${API_POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/quizfreely_postgres_password
      POSTGRES_DB_NAME: ${API_POSTGRES_DB_NAME}
      HOST: ${API_HOST}
      PORT: ${API_PORT}
      LOG_LEVEL: ${API_LOG_LEVEL}
      LOG_PRETTY: false
      CORS_ORIGIN: ${API_CORS_ORIGIN}
      ENABLE_OAUTH_GOOGLE: ${ENABLE_OAUTH_GOOGLE}
      OAUTH_GOOGLE_CLIENT_ID: ${API_OAUTH_GOOGLE_CLIENT_ID}
      OAUTH_GOOGLE_CLIENT_SECRET: ${API_OAUTH_GOOGLE_CLIENT_SECRET}
      OAUTH_GOOGLE_CALLBACK_URI: ${API_OAUTH_GOOGLE_CALLBACK_URI}
      OAUTH_REDIRECT_URL: ${API_OAUTH_REDIRECT_URL}
  quizfreely_web:
    image: quizfreely-web:0.31.0
    ports:
      - "8080:8080"
    links:
      - quizfreely_api
    environment:
      
  haproxy:
    image: docker.io/haproxytech/haproxy-debian:3.1.5
    configs:
      - source: haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
secrets:
  quizfreely_postgres_admin_password:
    external: true
  quizfreely_postgres_password:
    external: true
