version: "3"
services:
  postgres:
    image: docker.io/library/postgres:17.4-bookworm
    restart: unless-stopped
    secrets:
      - quizfreely_postgres_admin_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/quizfreely_postgres_admin_password
  quizfreely-api:
    image: codeberg.org/quizfreely/quizfreely-api:0.32.1
    restart: unless-stopped
    ports:
      - "8008:8008"
    links:
      - postgres
    secrets:
      - quizfreely_postgres_password
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${API_POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/quizfreely_postgres_password
      POSTGRES_DB_NAME: ${API_POSTGRES_DB_NAME}
      HOST: ${API_HOST}
      PORT: ${API_PORT}
      LOG_LEVEL: ${API_LOG_LEVEL}
      LOG_PRETTY: false
      CORS_ORIGIN: ${API_CORS_ORIGIN}
      ENABLE_OAUTH_GOOGLE: ${ENABLE_OAUTH_GOOGLE}
      OAUTH_GOOGLE_CLIENT_ID: ${API_OAUTH_GOOGLE_CLIENT_ID}
      OAUTH_GOOGLE_CLIENT_SECRET: ${API_OAUTH_GOOGLE_CLIENT_SECRET}
      OAUTH_GOOGLE_CALLBACK_URI: ${API_OAUTH_GOOGLE_CALLBACK_URI}
      OAUTH_REDIRECT_URL: ${API_OAUTH_REDIRECT_URL}
  quizfreely-web:
    image: codeberg.org/quizfreely/quizfreely-web:0.32.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    links:
      - quizfreely-api
    environment:
      HOST: ${WEB_HOST}
      PORT: ${WEB_PORT}
      ENABLE_OAUTH_GOOGLE: ${ENABLE_OAUTH_GOOGLE}
      API_URL: http://quizfreely-api:${API_PORT}
  caddy:
    image: docker.io/library/caddy:2.9.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    links:
      - quizfreely-web
      - quizfreely-api
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
secrets:
  quizfreely_postgres_admin_password:
    external: true
  quizfreely_postgres_password:
    external: true
volumes:
  caddy_data:
  caddy_config:
