http:
  routers:
    quizfreely-web:
      rule: "Host(`quizfreely.org`)"
      service: quizfreely-web
      middlewares:
        - compress
        - ratelimit
      tls:
        certResolver: certresolver
    quizfreely-api:
      rule: "Host(`quizfreely.org`) && PathPrefix(`/api`)"
      service: quizfreely-api
      middlewares:
        - compress
        - ratelimit
      tls:
        certResolver: certresolver
    others:
      rule: "Host(`www.quizfreely.org`) || Host(`quizfreely.com`) || Host(`www.quizfreely.com`)"
      middlewares:
        - redirect
      service: quizfreely-web
      tls:
        certResolver: certresolver
  services:
    quizfreely-web:
      loadBalancer:
        servers:
          - url: "http://quizfreely-web:8080"
    quizfreely-api:
      loadBalancer:
        servers:
          - url: "http://quizfreely-api:8008"
  middlewares:
    compression:
      compress:
        includedContentTypes:
          - application/json
          - application/javascript
          - text/html
          - text/css
          - text/plain
        encodings:
          - zstd
          - br
          - gzip
    ratelimit:
      rateLimit:
        average: 100
        period: 1s
        burst: 200
    redirect:
      redirectRegex:
        regex: "^https?://(www\.)?(quizfreely\.com|quizfreely\.org)(.*)"
        replacement: "https://quizfreely.org$3"
        permanent: true
