entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
providers:
  file:
    # traefik-dynamic.yaml is mounted to /etc/qzfr-traefik/config/traefik-dynamic.yaml in the compose file
    filename: "/etc/qzfr-traefik/config/traefik-dynamic.yaml"
    watch: false
api: false
certificatesResolves:
  certresolver:
    acme:
      email: admin@quizfreely.org
      # we define a named volume for /etc/qzfr-traefik/certs/ in your/our compose file
      storage: "/etc/qzfr-traefik/certs/acme.json"
      httpChallenge:
        entryPoint: web
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
