FROM node:22-alpine
# use non-root `node` user from node image
USER node
WORKDIR /home/node/quizfreely-api
COPY --chown=node:node package*.json ./
RUN npm ci --omit=dev
COPY --chown=node:node . .
EXPOSE 8008
ENV NODE_ENV=production
CMD [ "node", "index.js" ]
