name: End-to-End Tests
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  tests:
    name: Run Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: quizfreely_db_admin
          POSTGRES_PASSWORD: e2eTestsAdminPassword
          POSTGRES_DB: quizfreely_test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v6
        with:
          path: quizfreely
      - name: Clone quizfreely/api
        run: |
          set -euo pipefail
          cd quizfreely
          api_branch=$(yq '.api_branch' quizfreely.toml)
          if [[ -z "$api_branch" ]]; then
            api_branch="main"
          fi
          cd ../
          git clone \
            --depth 1 \
            --branch "$api_branch" \
            --single-branch \
            https://github.com/quizfreely/api.git api
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set Up Database
        env:
          PGPASSWORD: e2eTestsAdminPassword
          DB_MIGRATION_URL: 'postgres://quizfreely_db_admin:e2eTestsAdminPassword@localhost:5432/quizfreely_test_db?sslmode=disable'
        run: |
          set -euo pipefail
          psql -h localhost -U quizfreely_db_admin -d quizfreely_test_db -c "CREATE ROLE quizfreely_api LOGIN PASSWORD 'e2eTestsAPIPassword';"
          curl -fsSL -o dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          chmod +x dbmate
          cd api
          ../dbmate -e DB_MIGRATION_URL migrate
      - name: Set Up Garage Object Storage
        run: |
          set -euo pipefail
          curl -fsSL -o garage https://garagehq.deuxfleurs.fr/_releases/v2.2.0/x86_64-unknown-linux-musl/garage
          chmod +x garage
          cat <<EOF > garage.toml
          metadata_dir = "/tmp/meta"
          data_dir = "/tmp/data"
          db_engine = "sqlite"

          replication_factor = 1

          rpc_bind_addr = "0.0.0.0:3901"
          rpc_public_addr = "127.0.0.1:3901"
          rpc_secret = "$(openssl rand -hex 32)"

          [s3_api]
          s3_region = "garage"
          api_bind_addr = "0.0.0.0:3900"
          root_domain = ".s3.garage.localhost"

          [s3_web]
          bind_addr = "0.0.0.0:3902"
          root_domain = ".web.garage.localhost"
          index = "index.html"

          [admin]
          api_bind_addr = "0.0.0.0:3903"
          admin_token = "e2eTestsAdminToken"
          metrics_token = "e2eTestsMetricsToken"
          EOF
          ./garage -c garage.toml server &
          timeout 60s bash -c '
            until node_id=$(garage node id 2>/dev/null | cut -d'@' -f1); do
              sleep 1
            done
          '
          ./garage layout assign -z dc1 -c 1G "$node_id"
          ./garage layout apply --version 1
          ./garage bucket create usercontent
          ./garage bucket website --allow usercontent
          timeout 60s bash -c '
            until curl -fsSL --retry-connrefused --max-time 10 http://localhost:3903/health; do
              sleep 1
            done
          '
          create_key_resp=$(curl -fsSL -X POST "http://localhost:3903/v2/CreateKey" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer e2eTestsAdminToken" \
            -d '{ "name": "quizfreely-api" }')
          access_key_id=$(echo "$create_key_resp" | jq '.accessKeyId')
          secret_access_key=$(echo "$create_key_resp" | jq '.secretAccessKey')
          echo "STORAGE_ACCESS_KEY_ID=$access_key_id" >> $GITHUB_ENV
          echo "STORAGE_SECRET_ACCESS_KEY=$secret_access_key" >> $GITHUB_ENV
          ./garage bucket allow --read --write usercontent --key quizfreely-api
      - name: Create config.toml for API
        run: |
          set -euo pipefail
          cd api
          cat <<EOF > config.toml
          port = 8008
          db_url = 'postgres://quizfreely_api:e2eTestsAPIPassword@localhost:5432/quizfreely_test_db'
          pretty_log = true
          base_path = '/'
          enable_oauth_google = false
          storage_endpoint_url = 'http://localhost:3900'
          storage_region = "garage"
          storage_key_id = '$STORAGE_ACCESS_KEY_ID'
          storage_secret_key = '$STORAGE_SECRET_ACCESS_KEY'
          usercontent_bucket = "usercontent"
          usercontent_base_url = "http://localhost:8080/usercontent/"
          session_cleanup_cron_spec = "0 0 * * *"
          term_image_cleanup_cron_spec = "10 0 * * *"
          EOF
      - name: Start API
        run: |
          set -euo pipefail
          cd api
          go run main.go &
          timeout 30s bash -c '
            until curl -fsSL --retry-connrefused --max-time 10 http://localhost:8008/health; do
              sleep 1
            done
          '
      - name: Install Dependencies
        run: |
          cd quizfreely
          npm ci
      - name: Install Playwright Browsers
        #run: npx playwright install --with-deps
        run: npx playwright install chromium
      - name: Run Tests
        env:
          ENABLE_HTML_REPORTER: "${{ github.event_name != 'pull_request' }}"
          ENABLE_GH_REPORTER: true
          DEPLOYED: false
          ENABLE_OAUTH_GOOGLE: false
          ENABLE_TERM_IMAGES: true
          API_URL: http://localhost:8008
          USERCONTENT_URL: http://usercontent.web.garage.localhost:3902
        run: npx playwright test
      - name: Upload HTML Report
        if: always() && github.event_name != 'pull_request'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STORAGE_DEV_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STORAGE_DEV_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'garage'
          AWS_ENDPOINT_URL: 'http://server.quizfreely.org:3900'
        run: |
          REPORT_DIR='e2e-tests/run-${{ github.run_id }}-${{ github.run_attempt }}'
          aws s3 cp playwright-report s3://dev/$REPORT_DIR/ --recursive
          echo "### Test Report" >> $GITHUB_STEP_SUMMARY
          echo "View Test Report: https://dev.static.quizfreely.org/$REPORT_DIR/" >> $GITHUB_STEP_SUMMARY
