name: Update EhUI
on:
  workflow_dispatch:
jobs:
  update_ehui:
    name: Update EhUI
    runs-on: ubuntu-latest
    steps:
      - name: Clone quizfreely/quizfreely
        run: git clone https://github.com/quizfreely/quizfreely.git
      - name: Clone EhUI
        run: git clone https://github.com/ehanahamed/ehui.git
      - name: Copy compiled CSS
        run: |
          DATEYMD=$(date +%F)
          rm quizfreely/web/static/immutable/css/ehui-*.min.css
          rm quizfreely/web/static/immutable/themes/{auto,light,dark}-*.min.css
          mkdir -p quizfreely/web/static/immutable/css/
          mkdir -p quizfreely/web/static/immutable/themes/
          cp ehui/site/css/ehui.min.css "quizfreely/web/static/immutable/css/ehui-$DATEYMD.min.css"
          cp ehui/site/themes/auto-light-dark.min.css "quizfreely/web/static/immutable/themes/auto-$DATEYMD.min.css"
          cp ehui/site/themes/light.min.css "quizfreely/web/static/immutable/themes/light-$DATEYMD.min.css"
          cp ehui/site/themes/dark.min.css "quizfreely/web/static/immutable/themes/dark-$DATEYMD.min.css"
          sed -E -i \
            -e "s/ehui-[0-9]{4}-[0-9]{2}-[0-9]{2}.min.css/ehui-$DATEYMD.min.css/g" \
            -e "s/%theme%-[0-9]{4}-[0-9]{2}-[0-9]{2}.min.css/%theme%-$DATEYMD.min.css/g" \
            quizfreely/web/src/app.html
      - name: Commit & push
        run: |
          cd quizfreely
          git add .
          git config --global user.name "Ehan"
          git config --global user.email "ehanahamed@ehan.dev"
          git commit -m "Update EhUI"
          git push https://ehanahamed:${{ secrets.GH_TOKEN }}@github.com/quizfreely/quizfreely.git --all
