FROM node:22-alpine AS builder
WORKDIR /home/node/quizfreely-web
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
# if we have non-dev-dependencies:
#RUN npm prune --production

FROM node:22-alpine
# use non-root `node` user from node image
USER node
WORKDIR /home/node/quizfreely-web
COPY --chown=node:node --from=builder /home/node/quizfreely-web/build build/
# if we have non-dev-dependencies:
#COPY --chown=node:node --from=builder /home/node/quizfreely-web/node_modules node_modules/
COPY --chown=node:node package.json .
EXPOSE 8080
ENV NODE_ENV=production
CMD [ "node", "build/" ]
